syntax on
set number

noremap ; l
noremap l k
noremap k j
noremap j h

imap jj <Esc>

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
" Plugins in here

" Used for markdown stuff
call vundle#end()
filetype plugin indent on
