#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

# merge in defaults and keymaps

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
xrandr --output DP-0 --mode 2560x1440 --rate 165 --pos 1920x1080 --primary --output DVI-D-0 --pos 0x1080 --output HDMI-0 --pos 720x0

#/home/froppy/src/nasa-image-scraper/random_bg.sh
feh --bg-fill ~/Photos/Backgrounds/wenhop.jpg --bg-fill ~/Photos/Backgrounds/mate.jpg
numlockx &

# Based on current display, load different i3 config
# VNC display home
/home/froppy/.config/i3/genconfig-local.sh
if [ "$DISPLAY" = ":2" ]; then
    /home/froppy/.config/i3/genconfig-vnc2.sh
fi

# VNC display windows
if [ "$DISPLAY" = ":1" ]; then
    /home/froppy/.config/i3/genconfig-vnc1.sh
fi

# Local Display
if [ "$DISPLAY" = ":0"]; then
    /home/froppy/.config/i3/genconfig-local.sh
fi
#exec i3
