config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    chmod: '755'
  d_chrome:
    src: mozilla/firefox/godqu7jf.default-release/chrome
    dst: ~/.mozilla/firefox/godqu7jf.default-release/chrome
  d_ftplugin:
    src: vim/ftplugin
    dst: ~/.vim/ftplugin
profiles:
  Nova:
    dotfiles:
    - f_vimrc
    - f_bashrc
    - f_bash_profile
    - d_i3
    - d_dunst
    - d_neofetch
    - f_picom.conf
    - f_xresources
    - d_chrome
